config/routes.rb
Rails.application.routes.draw do
  resources :fish
  resources :carts
  resources :cart_items do
    put :add, on: :collection
    put :subb, on: :collection
  end
  devise_for :users
  resources :users
  resources :orders
  resources :news
  resources :addresses
  resources :categories do
    resources :products
  end
  resource :cart
  resources :products
  get "home", to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @news = News.all.order(last_edit_date: :desc)
  end

  def show
    @new = News.find(params[:id])
  end

  def new
    @new = News.new
  end

  def create
    @new = News.new(news_params)
    @new.save
    flash[:success] = "News has been created"
    redirect_to news_index_path
  end

  def edit
    @new = News.find(params[:id])
  end

  def update
    @new = News.find(params[:id])
    @new.update(news_edit_params)
    @new.save
    flash[:success] = "News has been updated"
    redirect_to news_index_path
  end

  private

  def news_params
    params.require(:news).permit(:content, :public, :title).merge(last_edit_date: DateTime.now, created_date: DateTime.now)
  end

  def news_edit_params
    params.require(:news).permit(:content, :public, :title).merge(last_edit_date: DateTime.now)
  end
end

app/views/news/edit.html.erb
<%=form_for @new, url: news_path(@new), method: :put do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% flash.each do |key, value| %>
   <span class="error_msgs">
     <div class="<%= flash_class(key) %>">
           <%= value %>
     </div>
     </span>
    <script>
    setTimeout("$('.error_msgs').fadeOut('slow')", 1000)
  </script>
<% end %>

app/views/news/index.html.erb
<%= link_to 'New', new_news_path, method: :get, class: "btn btn-dark" %>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Created Date</th>
      <th>Last Edit Date</th>
      <th>Public</th>
      <th></th>
    <tr>
  </thead>
  <tbody>
    <% @news.each do |new| %>
      <tr>
        <th><%= new.title %></th>
        <td><%= new.created_date %></td>
        <td><%= new.last_edit_date %></td>
        <td><%= new.public %></td>
        <td>
          <%= link_to 'Show', news_path(new), class: "btn btn-outline-dark" %>
          <%= link_to 'Edit', edit_news_path(new), class: "btn btn-outline-dark" %>
        </td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/news/new.html.erb
<%=form_for @new, url: {action: "create"} do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% flash.each do |key, value| %>
   <span class="error_msgs">
     <div class="<%= flash_class(key) %>">
           <%= value %>
     </div>
     </span>
    <script>
    setTimeout("$('.error_msgs').fadeOut('slow')", 1000)
  </script>
<% end %>

app/views/news/show.html.erb
<%= @new.content %>