config/routes.rb
Rails.application.routes.draw do
  resources :fish
  resources :carts
  resources :cart_items do
    put :add, on: :collection
    put :subb, on: :collection
  end
  devise_for :users
  resources :users
  resources :orders
  resources :news
  resources :addresses
  resources :categories do
    resources :products
  end
  resource :cart
  resources :products
  get "home", to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # to show cart user must be logged in
  before_action :authenticate_user!
  def show
    @cart = current_user.cart
  end

  def create
    @cart = Cart.create(user_id: current_user(:id))
    @cart.save
  end

  def destroy
    current_user.cart.cart_items.each do |item|
      item.destroy
    end
    redirect_to cart_path
  end
end

app/views/carts/show.html.erb
<h1> Cart </h1>
<% accept = true %>
<!-- creating table to list items in cart -->
<%  if @cart %>
  <%= link_to "Clean Cart", @cart, method: :delete %>
  <!--heads -->
  <table class="table table-hover">
    <thead class="thead-dark">
        <th>Product</th>
        <th>Quantity>
        <th>Price</th>
        <th>In Stock</th>
        <th></th>
    </thead>
    <!-- items -->
    <tbody>
      <% @cart.cart_items.each do |item| %>
        <tr>
          <th><%= item.product(item.product_id).name  %></th>
          <td><%= item.quantity %></td>
          <td><%= number_with_precision(item.product(item.product_id).price * item.quantity, precision: 2 )%> zł </td>
          <td><%= item.product(item.product_id).in_stock %></td>
          <td>
            <!-- link to call add or subb method from cart_item_controller -->
            <%= link_to "Add",  add_cart_items_path(params: {product_id: item.product_id}), method: :put %>
            <%= link_to "Subtract", subb_cart_items_path(params: {product_id: item.product_id}), method: :put %>
          </td>
        <tr>
        <!-- check if placing an order is possible-->
        <% if item.quantity > item.product(item.product_id).in_stock %>
          <% accept = false %>
        <% end  %>
      <% end %>
    </tbody>
  </table>
<%  else  %>
  KOSZYK JEST PUSTY
<% end %>

<% if accept == true   %>
  <!-- placing order -->
  <%= link_to "place an order", new_order_path  %>
<% else  %>
  Cant place order Quantity of some product is higher than products in stock
<% end  %>