config/routes.rb
Rails.application.routes.draw do
  resources :fish
  resources :carts
  resources :cart_items do
    put :add, on: :collection
    put :subb, on: :collection
  end
  devise_for :users
  resources :users
  resources :orders
  resources :news
  resources :addresses
  resources :categories do
    resources :products
  end
  resource :cart
  resources :products
  get "home", to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :serial_numbers
  has_many :order_items
  belongs_to :manufacturer
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    search_query = products_by_search_query(params[:search])
    category = params[:category_id]
    # using string from products_by_search_query to create complete query
    if category.present?
      @products = Product.where(category_id: category).where(search_query).joins(:category, :manufacturer)
    else
      @products = Product.where(search_query).joins(:category, :manufacturer)
    end
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  def edit
    @product = Product(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to products_path
  end

  def update
    @product = Product.find(params[:id])
  	@product.update(product_params)
    @product.save
    flash[:success] = "Status has been updated"
    redirect_to products_path
  end

  private

  #creating part of sql query using params
  def products_by_search_query(search)
    if search.present?
      search_string =  '%' + search + '%'
      search_query = '"categories"."category_name" ILIKE :search_string OR
      "manufacturers"."manufacturer_name" ILIKE :search_string OR
       "products"."name" ILIKE :search_string',
      {search_string: search_string }
    end
    search_query
  end

  def product_params
    params.require(:product).permit(
      :name,
      :category_id,
      :manufacturer_id,
      :parameters,
      :description,
      :in_stock,
      :price,
      :package_specification,
      :product_code
    )
  end

end

app/views/products/index.html.erb
<h1> Products </h1>

<% if current_user && current_user.access_level = 1 %>
  <%= link_to "New", new_product_path, method: :get, class: "btn btn-dark" %>
<% end %>

<%= form_tag(products_path, method: :get)  do%>
  <%= text_field_tag  :search, params[:search], class: "col-lg-3"%>
  <%= submit_tag "Search" %>
<% end %>
<table class="table table-hover">
  <thead class="thead-dark">
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>In Stock</th>
      <th>product_code</th>
      <th></th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <%= product.name %> </td>
        <td> <%= product.category.category_name %> </td>
        <td>
          <%= number_with_precision(
          product.price, precision: 2
          )%> zł
        </td>
        <td><%= product.in_stock %></td>
        <td><%= product.product_code %></td>
        <td><%= link_to 'Show Product', product, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%=form_for @product, url: {action: "create"} do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category_id, Category.all.collect { |c| [ c.category_name, c.id ] }) %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.select(:manufacturer_id, Manufacturer.all.collect { |m| [ m.manufacturer_name, m.id ] }) %>
  </div>

  <div class="field">
    <%= form.label :parameters %>
    <%= form.text_area :parameters %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :in_stock %>
    <%= form.text_field :in_stock %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :package_specification %>
    <%= form.text_field :package_specification %>
  </div>

  <div class="field">
    <%= form.label :product_code %>
    <%= form.text_field :product_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% flash.each do |key, value| %>
   <span class="error_msgs">
     <div class="<%= flash_class(key) %>">
           <%= value %>
     </div>
     </span>
    <script>
    setTimeout("$('.error_msgs').fadeOut('slow')", 1000)
  </script>
<% end %>

app/views/products/show.html.erb
<%= form_tag(products_path, method: :get)  do%>
  <%= text_field_tag  :search, params[:search], class: "col-lg-3"%>
  <%= submit_tag "Search" %>
<% end %>
<div class="list-group col-lg-5">
  <ul>
    <li type="li" class="list-group-item list-group-item-secondary">
      <%= @product.name %>
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      Category:  <%= @product.category.category_name %>
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      Manufacurer: <%= @product.manufacturer.manufacturer_name %>
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      Parameters: <%= @product.parameters %>
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      Package Specification <%= @product.package_specification %>
    </li>
  </ul>
</div>

<div class="list-group col-lg-5">
  <ul>
    <li type="li" class="list-group-item list-group-item-secondary">
      PRICE
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      <%= number_with_precision(
      @product.price, precision: 2
      )%> zł
    </li>
  </ul>
</div>

<div class="list-group col-lg-5">
  <ul>
    <li type="li" class="list-group-item list-group-item-secondary">
      IN STOCK
    </li>
    <li type="li" class="list-group-item list-group-item-action">
      <%= @product.in_stock %>
    </li>
  </ul>
</div>

<!-- form to create item in cart -->
<%= form_for @cart_item, url: cart_items_path, method: :post do |f| %>
  <div class="form-group">
    <!-- choosing quantity -->
    QUANTITY: <%= f.text_field :quantity,  value: 1 %>
    <%= f.hidden_field :product_id, value: @product.id %>
  </div>

  <div class="form-group">
    <% if current_user %>
      <!-- submit quantity and adding to cart -->
      <%= f.submit 'Add to Cart', class: "btn btn-outline-dark" %>
    <% else %>
      <!-- redirect to sign in tab if user not logged in -->
      <%= link_to('Add to Cart', new_user_session_path, class: "btn btn-outline-dark")  %>
    <% end  %>
  </div>
<% end %>
<%= @product.description %>