config/routes.rb
Rails.application.routes.draw do
  resources :fish
  resources :carts
  resources :cart_items do
    put :add, on: :collection
    put :subb, on: :collection
  end
  devise_for :users
  resources :users
  resources :orders
  resources :news
  resources :addresses
  resources :categories do
    resources :products
  end
  resource :cart
  resources :products
  get "home", to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  has_many :orders

  def full_address
    if street.present?
      if apartment_number.present?
        city + " " + postcode + " " + street + " " + house_number + "/" + apartment_number
      else
        city + " " + postcode + " " + street + " " + house_number
      end
    else
      if apartment_number.present?
        postcode + " " + city + " " + house_number + "/" + apartment_number
      else
        postcode + " " + city + " " + house_number
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart

  def product(id)
    Product.find(id)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_many :addresses

  def name
    first_name + " " + last_name
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :address
  belongs_to :customer
  belongs_to :status


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def count_price
    price * count
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :serial_numbers
  has_many :order_items
  belongs_to :manufacturer
  belongs_to :category
end

app/models/serial_number.rb
class SerialNumber < ApplicationRecord
  belongs_to :product
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
  has_one :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # to show cart user must be logged in
  before_action :authenticate_user!
  def show
    @cart = current_user.cart
  end

  def create
    @cart = Cart.create(user_id: current_user(:id))
    @cart.save
  end

  def destroy
    current_user.cart.cart_items.each do |item|
      item.destroy
    end
    redirect_to cart_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news =  News.where(public: true).last(5)
    @categories = Category.all
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @news = News.all.order(last_edit_date: :desc)
  end

  def show
    @new = News.find(params[:id])
  end

  def new
    @new = News.new
  end

  def create
    @new = News.new(news_params)
    @new.save
    flash[:success] = "News has been created"
    redirect_to news_index_path
  end

  def edit
    @new = News.find(params[:id])
  end

  def update
    @new = News.find(params[:id])
    @new.update(news_edit_params)
    @new.save
    flash[:success] = "News has been updated"
    redirect_to news_index_path
  end

  private

  def news_params
    params.require(:news).permit(:content, :public, :title).merge(last_edit_date: DateTime.now, created_date: DateTime.now)
  end

  def news_edit_params
    params.require(:news).permit(:content, :public, :title).merge(last_edit_date: DateTime.now)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
      case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-danger"
        when 'alert' then "alert alert-warning"
      end
  end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectShop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#"> SuperShop </a>
      <button
        class="navbar-toggler"
        type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <button type="button" class="btn btn-dark"><%= link_to 'Home', home_path %></button>
          </li>

          <li class="nav-item active">
            <button type="button" class="btn btn-dark"><%= link_to 'Products', products_path %></button>
          </li>
          <!-- only order fulfillment has access to orders tab-->
          <% if current_user.present? && current_user.access_level == 2 %>
            <li class="nav-item active">
              <button type="button" class="btn btn-dark"><%= link_to 'Orders', orders_path %></button>
            </li>
          <% end  %>
          <!-- only admin has access to news editor -->
          <% if current_user.present? && current_user.access_level == 1 %>
            <li class="nav-item active">
              <button type="button" class="btn btn-dark"><%= link_to 'News', news_index_path %></button>
            </li>
          <% end  %>
          <!-- only admin has access to all users listing-->
          <% if current_user.present? && current_user.access_level == 1 %>
            <li class="nav-item active">
              <button type="button" class="btn btn-dark"><%= link_to 'Users', users_path %></button>
            </li>
          <% end  %>
          <!-- user must be logged in to show his cart -->
          <%if current_user %>
          <li class="nav-item active">
            <button type="button" class="btn btn-dark"><%= link_to 'MY CART', cart_path(current_user.id) %></button>
          </li>
          <%  end %>
        </ul>

        <% if user_signed_in? %>
          <span>
            <!-- user must be logged in to show his profile -->
            <%= link_to('MY PROFILE', user_path(current_user)) %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </span>
        <% else %>
          <span>
            <%= link_to('Login', new_user_session_path)  %>
          </span>
        <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>